### ISSUE TITLE
Title Bar not relocated by `add_title(.., title_position)`?

### ISSUE THREAD

**Issue by psychemedia** [tylermorganwall/rayimage#3]
If I use the `title_position` argument to `rayshader::add_title()` (for example, `title_position='south') when constructing a `rayshader` image, the text label is relocated but the `title_bar` seems to be stuck in place at the top of the image rather than also being relocated so it continues to sit behind the title?

Speaking as a user (rather than an R developer, which I'm not!), a couple of other things I have noticed in terms of function usability that could make `add_title()` more powerful, eg for overlaying "TV style" transparent graphics:

- the title bar is overlaid by default on top of the first few rows of image data. It would be useful to have an option to add the title bar so that it abuts the image (which would increase the image height by the height of the title) and then perhaps offer an option to rescale the image back to its original height (and rescale the width in a similar proportion, adding a user choice coloured buffer to pad left and right). title bars to left and right, perhaps with rotate text might also be useful;
- for TV graphics style text overlays, it would be useful to set the width of the title bar when used with something like `title_position='center'`, perhaps allow a percentage width to be specified (so eg `width_pc=80` would have a width of 80% of the image width).

**Comment by psychemedia** [comment]
I also note that if I have a title over several lines (eg `title_text="Title\nSubtitle"`) the size of the title bar does not expand and the text overflows into the area below the title bar.

**Comment by tylermorganwall** [comment]
The latest version should fix this issue, and you can also now specify the width of the title bar yourself (which should allow you to fit your multi-line titles). As for the other items, I'd recommend opening feature request issues for each request (which makes them more manageable from my POV).
