### ISSUE TITLE
rayimage citation

### ISSUE THREAD

**Issue by srfall** [tylermorganwall/rayimage#5]
Hey, 
I just wanted to open an issue in case my mail gets lost: I'm developing an r package (also GPL-3) in which one function is based on / inspired by rayimage code and I wanted to check in to see if you are satisfied with the way you are acknowleged or if you have any other preferences. 

Here are the current citations / acknowlegements:
https://github.com/metaRange/metaRange/blob/main/inst/COPYRIGHTS
https://github.com/metaRange/metaRange/blob/main/src/dispersal.cpp#L23

My main questions are: Should I change anything there & would you also like to be mentioned in the Authors@R field of the description?

Also, thanks for this great package!

**Comment by tylermorganwall** [comment]
I believe the official CRAN policy is to acknowledge all code contributors/copyright holders in the DESCRIPTION Authors@R field, and then describe the details in the COPYRIGHTS file (as you have already done). 

You can add `person("Tyler", "Morgan-Wall", role = c("ctb", "cph"), comment = c(ORCID = "0000-0002-3131-3814"))` and that you should be set. Thanks for taking the effort to cite!

**Comment by srfall** [comment]
Alright, done in https://github.com/metaRange/metaRange/commit/c8270c39318b143754206aec3387d0dcc8eee543
